# Removed some things that are not used, in the config and in the plugin code.
# If you need help you can consult the discord server: https://discord.com/invite/3RRWVTGveD
# Bungee mode Requires 2 servers obviously, more options will be added for this.
debugMode: false
bungeeMode:
  enabled: false
  autoJoin: false
  kickOnStarted: false
  sendLobbyOnQuit: false
  kickOnFinish: false
  lobbyServer: lobby
addons:
  placeholdersAPI: true
mainLobby: null
mobGriefing: false
progressBarAmount: 10
excluideDefKits: true
kitLevelsOrder: true
lobbyScoreboard: true
statsCMD: true
updatePlayersPlaceholder: 5
breakMap:
  enabled: true
  totalBreak: true
  bypass:
    - WEB
    - GOLD_BLOCK
    - IRON_BLOCK
redPanelInLocked: true
redPanel:
  material: STAINED_GLASS_PANE
  data: 14
gameDefaults:
  autoJoinFinish: false
  woolRadio: false
  hunger: false
  instaKillOnVoid: true
  supportItems: true
  noFallDamage: true
  maxMultiplier: 4
  starting: 30
  timeToKill: 30
  limitOfYSpawn: 40
  gcoins:
    kill: 3
    win: 10
    capture: 10
  coins:
    kill: 5
    win: 20
    capture: 10
  xp:
    kill: 5
    win: 10
    capture: 10
  noDrop:
    - WOOL
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - IRON_PICKAXE
    - IRON_AXE
    - ARROW
    - WOOD
    - BOW
    - IRON_SWORD
    - STONE_SWORD
    - DIAMOND_SWORD
    - PLANKS
bounty:
  min: 90
  max: 110
  perKill: 0.10
chat:
  joinMessage: true
  broadcastGame: true
items:
  lobby:
    enabled: false
    slot: 4
    cmd: /ctw lobby
  lobby2:
    enabled: false
    slot: 0
    cmd: /ctw join
materials:
  lobby: DIAMOND
  closeitem: BOOK
win-commands:
  enabled: false
  cmds:
    - "say <player> is a pro!"
lose-commands:
  enabled: true
  cmds:
    - "say <player> is a loser!"
level-commands:
  enabled: false
  cmds:
    - "say <player> level up!"
death-commands:
  enabled: false
  cmds:
    - "say <player> is a noob!"
kill-commands:
  enabled: false
  cmds:
    - "say <player> is a killer!"
whitelistedCMD:
  - /leave
  - /msg
  - /stats
  - /join
  - /tell
  - /r
  - /ping